### ISSUE TITLE
Change formspree lines to https rather than http

### ISSUE THREAD

**Issue by caperren** [OSURoboticsClub/resiSTORE#1]
Added https certificates to website, but it won't show up as secure if you load any http content from within the page. Lines 226 and 256 of index.html need the formspree urls changed to https:// . I've modified the versions directly on the server at the moment and verified that it still works when changed.

**Comment by caperren** [comment]
I'm going to expand this issue to, please change ALL references to resources (images, files, etc...) to be relative paths, rather than absolute ones. This will ensure that the content is automatically loaded via https rather than http. If you do have to load any content via explicit urls (like the formspree one) you need to use the secure version of the URL.

That being said, if the item is just a hyperlink to take you to a new page, that's fine and can remain http.

**Comment by thegrims** [comment]
Changed all the http links outside of direct url links to https. Also added relative paths.
